// ============================================================================
// Export.GCode — Drawing -> G-code (ISO 6983 / RS-274) for CNC milling
// machines. Generates toolpaths for each layer based on its machining
// parameters (side, depth, millType). Each layer's contours become one or
// more cutting passes at incremental depths, with proper lead-in/lead-out
// and optional climb/conventional milling direction.
//
// Output format: Standard G-code with comments in parentheses for layer
// names and operation descriptions. Uses G17 (XY plane), G20/G21 (units),
// G0/G1 (rapid/feed moves), G2/G3 (arcs), G40/G41/G42 (cutter comp).
//
// Supports separate programs for:
// - Top and bottom sides (bottom side is mirrored horizontally)
// - Different tools based on cutting depth:
//   * Tool 1: Ø4mm, length 22mm - for depths <= 15mm
//   * Tool 2: Ø8mm, length 42mm - for depths > 15mm
// Files are named: {name}_{side}_T{toolNum}.nc
// When multiple files are generated, they are bundled in a ZIP archive.
// ============================================================================
const ExportGCode = (() => {
  // === Tool Definitions =====================================================
  const TOOLS = {
    T1: {
      id: 'T1',
      diameter: 4,        // mm
      length: 22,         // mm
      maxDepth: 15,       // mm - maximum cutting depth for this tool
      spindleSpeed: 18000,// RPM
      feedRateCut: 2500,  // mm/min
      feedRatePlunge: 400,// mm/min
      description: 'Фреза Ø4мм, L=22мм (до 15мм глубины)'
    },
    T2: {
      id: 'T2',
      diameter: 8,        // mm
      length: 42,         // mm
      maxDepth: 100,      // mm - maximum cutting depth for this tool
      spindleSpeed: 12000,// RPM
      feedRateCut: 3000,  // mm/min
      feedRatePlunge: 500,// mm/min
      description: 'Фреза Ø8мм, L=42мм (глубокая фрезеровка)'
    }
  };

  // === Configuration ========================================================
  const CONFIG = {
    // Units: true = inches (G20), false = mm (G21)
    useInches: false,
    
    // Arc settings
    arcMode: 'R12',         // 'R12' = use R format, 'IJ' = use IJ format
    
    // Safety heights
    clearanceHeight: 5,     // Height above material for rapid moves
    plungeIncrement: 3,     // Max depth per pass (mm)
    
    // Depth threshold for tool selection (mm)
    depthThreshold: 15,     // Use T1 (4mm) for depths <= 15mm, T2 (8mm) for deeper
  };

  // Convert mm to inches if needed
  function toUnits(mm) {
    return CONFIG.useInches ? mm / 25.4 : mm;
  }

  // Format number for G-code output
  function fmt(value, decimals = 4) {
    const v = toUnits(Number(value));
    return v.toFixed(decimals).replace(/\.?0+$/, '');
  }

  // Mirror contour horizontally (flip Y coordinate for bottom side)
  // The workpiece origin is at bottom-left, so mirroring across X-axis
  // means negating Y coordinates relative to the workpiece height
  function mirrorContour(contour, workpieceHeight) {
    return contour.map(pt => ({
      x: pt.x,
      y: workpieceHeight - pt.y,
      bulge: -pt.bulge  // Negate bulge to preserve arc direction after mirroring
    }));
  }

  // Select tool based on cutting depth
  function selectTool(depth) {
    const absDepth = Math.abs(depth);
    // Use T1 (4mm) for depths <= 15mm, T2 (8mm) for deeper cuts
    return absDepth <= CONFIG.depthThreshold ? TOOLS.T1 : TOOLS.T2;
  }

  // Generate G-code header for a specific tool
  function buildHeader(sideName, tool) {
    const lines = [];
    lines.push('%');
    lines.push(`(Generated by DSK Editor G-code Generator)`);
    lines.push(`(Date: ${new Date().toISOString()})`);
    lines.push(`(Side: ${sideName})`);
    lines.push(`(Tool: ${tool.description})`);
    lines.push('(Units: ' + (CONFIG.useInches ? 'Inches (G20)' : 'Millimeters (G21)') + ')');
    lines.push('');
    lines.push('(=== Setup ===)');
    lines.push('G17');           // XY plane
    lines.push('G40');           // Cancel cutter compensation
    lines.push('G49');           // Cancel tool length offset
    lines.push('G80');           // Cancel canned cycles
    lines.push(CONFIG.useInches ? 'G20' : 'G21');  // Units
    lines.push('G90');           // Absolute positioning
    lines.push('G54');           // Work coordinate system 1
    lines.push('');
    lines.push('(=== Tool Setup ===)');
    lines.push(`${tool.id}`);    // Select tool (no M6 since machine doesn't support tool change)
    lines.push(`S${tool.spindleSpeed} M3`);  // Spindle on with tool-specific RPM
    lines.push(`G43 ${tool.id.replace('T', 'H')} Z${fmt(CONFIG.clearanceHeight)}`);  // Tool length offset
    lines.push('M8');            // Coolant on
    lines.push('');
    return lines;
  }

  // Calculate center and radius from bulge arc
  function getArcCenter(p1, p2, bulge) {
    const chord = Math.hypot(p2.x - p1.x, p2.y - p1.y);
    if (Math.abs(bulge) < 1e-9 || chord < 1e-9) {
      return null; // Straight line
    }
    const radius = Math.abs(chord * (1 + bulge * bulge) / (4 * Math.abs(bulge)));
    const sagitta = chord * bulge / 2;
    
    // Midpoint of chord
    const mx = (p1.x + p2.x) / 2;
    const my = (p1.y + p2.y) / 2;
    
    // Perpendicular direction
    const dx = p2.x - p1.x;
    const dy = p2.y - p1.y;
    const len = Math.hypot(dx, dy) || 1;
    const nx = -dy / len;
    const ny = dx / len;
    
    // Center is perpendicular to chord at distance from midpoint
    const dist = Math.sqrt(radius * radius - (chord / 2) * (chord / 2));
    const sign = bulge > 0 ? 1 : -1;
    
    return {
      cx: mx + nx * dist * sign,
      cy: my + ny * dist * sign,
      radius: radius,
      sweep: Math.abs(4 * Math.atan(bulge))
    };
  }

  // Generate G-code for a single contour at a specific depth
  function buildContourGCode(contour, layerName, depth, passNum, totalPasses, materialThickness, sideName, tool) {
    const lines = [];
    const n = contour.length;
    if (n < 2) return lines;

    const layerInfo = Layers.get(layerName);
    const machining = layerInfo ? layerInfo.machining : null;
    
    // Determine cut side based on millType
    let comment = `Layer: ${layerName}, Pass ${passNum}/${totalPasses}, Depth: ${fmt(depth)}mm`;
    if (machining) {
      comment += ` (${machining.side} side, ${machining.millType})`;
    }
    lines.push(`(${comment})`);

    // Start point
    const startX = contour[0].x;
    const startY = contour[0].y;
    
    // Rapid to start position at clearance height
    lines.push(`G0 X${fmt(startX)} Y${fmt(startY)}`);
    
    // Plunge to current depth with tool-specific feed rate
    const plungeFeed = tool ? tool.feedRatePlunge : CONFIG.feedRatePlunge;
    lines.push(`G1 Z${fmt(depth)} F${plungeFeed}`);
    
    // Cut the contour with tool-specific feed rate
    const cutFeed = tool ? tool.feedRateCut : CONFIG.feedRateCut;
    for (let i = 0; i < n; i++) {
      const cur = contour[i];
      const next = contour[(i + 1) % n];
      
      if (Math.abs(cur.bulge) < 1e-9) {
        // Straight line
        lines.push(`G1 X${fmt(next.x)} Y${fmt(next.y)} F${cutFeed}`);
      } else {
        // Arc segment
        const arcInfo = getArcCenter(cur, next, cur.bulge);
        if (arcInfo) {
          const dir = cur.bulge > 0 ? 'G3' : 'G2'; // CCW = G3, CW = G2
          
          if (CONFIG.arcMode === 'R12') {
            // R format
            const r = arcInfo.radius;
            const largeArc = arcInfo.sweep > Math.PI ? 1 : 0;
            lines.push(`${dir} X${fmt(next.x)} Y${fmt(next.y)} R${fmt(r)}`);
          } else {
            // IJ format
            const i = arcInfo.cx - cur.x;
            const j = arcInfo.cy - cur.y;
            lines.push(`${dir} X${fmt(next.x)} Y${fmt(next.y)} I${fmt(i)} J${fmt(j)}`);
          }
        } else {
          // Fallback to line if arc calculation fails
          lines.push(`G1 X${fmt(next.x)} Y${fmt(next.y)} F${cutFeed}`);
        }
      }
    }
    
    // Retract to clearance height
    lines.push(`G0 Z${fmt(CONFIG.clearanceHeight)}`);
    lines.push('');
    
    return lines;
  }

  // Generate multi-pass cutting for a contour with specific tool
  function buildMultiPassContour(contour, layerName, machining, materialThickness, sideName, tool) {
    const lines = [];
    
    // Determine target depth
    let targetDepth = 0;
    let depthAnchor = 'bottom';
    
    if (machining && machining.depth !== undefined && machining.depth !== 'none') {
      targetDepth = machining.depth;
      depthAnchor = machining.depthAnchor || 'bottom';
      
      // Calculate absolute depth based on anchor
      if (depthAnchor === 'top') {
        targetDepth = -targetDepth; // Cut from top, depth is negative
      } else if (depthAnchor === 'center') {
        targetDepth = -(materialThickness / 2 + targetDepth);
      } else {
        // bottom anchor
        targetDepth = -targetDepth;
      }
    }
    
    // For through cuts (depth = 0 with top anchor), cut through entire thickness
    if (machining && machining.depth === 0 && machining.depthAnchor === 'top') {
      targetDepth = -materialThickness;
    }
    
    // Calculate number of passes
    const numPasses = Math.ceil(Math.abs(targetDepth) / CONFIG.plungeIncrement);
    const actualIncrement = Math.abs(targetDepth) / numPasses;
    
    // Generate passes
    for (let pass = 1; pass <= numPasses; pass++) {
      const depth = targetDepth * (pass / numPasses);
      const passLines = buildContourGCode(contour, layerName, depth, pass, numPasses, materialThickness, sideName, tool);
      lines.push(...passLines);
    }
    
    return lines;
  }

  // Build G-code for one side and one tool
  function buildForSideAndTool(entries, params, side, tool) {
    const lines = buildHeader(side === 'top' ? 'Лицевая сторона' : 'Тыльная сторона', tool);
    const materialThickness = params.thickness || 30;
    const workpieceHeight = params.H || 0;
    
    lines.push('(=== Begin Cutting Operations ===)');
    lines.push('');
    
    // Group contours by layer
    const byLayer = {};
    for (const entry of entries) {
      const layer = entry.layer || 'OUTLINE';
      if (!byLayer[layer]) {
        byLayer[layer] = [];
      }
      byLayer[layer].push(entry);
    }
    
    // Process each layer
    const layerOrder = Object.keys(byLayer);
    for (const layerName of layerOrder) {
      const contours = byLayer[layerName];
      const layerInfo = Layers.get(layerName);
      const machining = layerInfo ? layerInfo.machining : null;
      
      // Skip layers that don't match the requested side
      if (!machining || machining.depth === 'none' || machining.side !== side) {
        continue;
      }
      
      // Check if this layer's depth matches the tool
      let layerDepth = machining.depth || 0;
      if (machining.depth === 0 && machining.depthAnchor === 'top') {
        layerDepth = materialThickness; // Through cut
      } else if (machining.depthAnchor === 'top') {
        layerDepth = machining.depth;
      }
      
      // Select tool for this layer based on depth
      const layerTool = selectTool(layerDepth);
      if (layerTool.id !== tool.id) {
        continue; // Skip this layer - it uses a different tool
      }
      
      lines.push(`(=== Layer: ${layerName} ===)`);
      
      // Process each contour in this layer
      for (let i = 0; i < contours.length; i++) {
        const { contour, closed = true } = contours[i];
        if (!contour || contour.length < 2) continue;
        
        lines.push(`(Contour ${i + 1}/${contours.length})`);
        
        // Mirror contour for bottom side
        const processedContour = side === 'bottom' 
          ? mirrorContour(contour, workpieceHeight)
          : contour;
        
        const passLines = buildMultiPassContour(processedContour, layerName, machining, materialThickness, side, tool);
        lines.push(...passLines);
      }
    }
    
    // End of program
    lines.push('(=== End of Program ===)');
    lines.push('G0 Z' + fmt(CONFIG.clearanceHeight + 10)); // Safe retract
    lines.push('M5');  // Spindle off
    lines.push('M9');  // Coolant off
    lines.push('G91 G28 Z0'); // Home Z axis
    lines.push('G28 X0 Y0');  // Home X and Y axes
    lines.push('M30'); // Program end and reset
    lines.push('%');
    
    return lines.join('\n');
  }

  // Build G-code for one side (combines both tools) - kept for backward compatibility
  function buildForSide(entries, params, side) {
    const materialThickness = params.thickness || 30;
    
    // Determine which tools are needed for this side
    const toolsNeeded = new Set();
    for (const entry of entries) {
      const layerInfo = Layers.get(entry.layer || 'OUTLINE');
      const machining = layerInfo ? layerInfo.machining : null;
      if (!machining || machining.depth === 'none' || machining.side !== side) {
        continue;
      }
      
      let layerDepth = machining.depth || 0;
      if (machining.depth === 0 && machining.depthAnchor === 'top') {
        layerDepth = materialThickness;
      } else if (machining.depthAnchor === 'top') {
        layerDepth = machining.depth;
      }
      
      const tool = selectTool(layerDepth);
      toolsNeeded.add(tool.id);
    }
    
    // If only one tool is needed, use buildForSideAndTool directly
    if (toolsNeeded.size === 1) {
      const toolId = Array.from(toolsNeeded)[0];
      const tool = toolId === 'T1' ? TOOLS.T1 : TOOLS.T2;
      return buildForSideAndTool(entries, params, side, tool);
    }
    
    // Multiple tools needed - combine them (this shouldn't happen in new logic)
    const gcode1 = buildForSideAndTool(entries, params, side, TOOLS.T1);
    const gcode2 = buildForSideAndTool(entries, params, side, TOOLS.T2);
    
    // Only return non-empty results
    const has1 = gcode1 && gcode1.includes('(=== Layer:');
    const has2 = gcode2 && gcode2.includes('(=== Layer:');
    
    if (has1 && has2) {
      return gcode1 + '\n\n' + gcode2;
    } else if (has1) {
      return gcode1;
    } else {
      return gcode2;
    }
  }

  // Main build function (backward compatibility - builds for all sides combined)
  function build(entries, params) {
    // For backward compatibility, combine both sides into one file
    const topGcode = buildForSide(entries, params, 'top');
    const bottomGcode = buildForSide(entries, params, 'bottom');
    
    return topGcode + '\n\n' + bottomGcode;
  }

  // Download G-code files as ZIP archive (separate files per side and tool)
  function downloadAs(entries, params, filename) {
    let name = (filename || 'program').trim();
    if (!name) name = 'program';
    
    const materialThickness = params.thickness || 30;
    const files = [];
    
    // Generate G-code for each side and tool combination
    const sides = ['top', 'bottom'];
    const tools = [TOOLS.T1, TOOLS.T2];
    
    for (const side of sides) {
      for (const tool of tools) {
        const gcode = buildForSideAndTool(entries, params, side, tool);
        
        // Check if this file has content
        const hasContent = gcode && gcode.includes('(=== Layer:');
        if (!hasContent) continue;
        
        // Create filename: {name}_{side}_T{toolNum}.nc
        const sideSuffix = side === 'top' ? 'top' : 'bottom';
        const toolSuffix = tool.id.toLowerCase(); // t1 or t2
        let fname = `${name}_${sideSuffix}_${toolSuffix}.nc`;
        
        files.push({ name: fname, content: gcode });
      }
    }
    
    if (files.length === 0) {
      alert('Нет данных для экспорта G-code.');
      return;
    }
    
    // If only one file, download directly
    if (files.length === 1) {
      const blob = new Blob([files[0].content], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = files[0].name;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      setTimeout(() => URL.revokeObjectURL(url), 1000);
      return;
    }
    
    // Multiple files - create ZIP archive
    createZipAndDownload(files, name + '.zip');
  }
  
  // Create ZIP archive from files and trigger download
  function createZipAndDownload(files, zipFilename) {
    // Simple ZIP file creator (minimal implementation without external libraries)
    // ZIP file format: local file headers + file data + central directory + end of central directory
    
    const encoder = new TextEncoder();
    const parts = [];
    const centralDirectory = [];
    let offset = 0;
    
    for (const file of files) {
      const filenameBytes = encoder.encode(file.name);
      const contentBytes = encoder.encode(file.content);
      const crc32 = calculateCRC32(contentBytes);
      
      // Local file header
      const localHeader = new ArrayBuffer(30 + filenameBytes.length);
      const localView = new DataView(localHeader);
      
      // Signature
      localView.setUint32(0, 0x04034b50, true);
      // Version needed
      localView.setUint16(4, 20, true);
      // General purpose bit flag
      localView.setUint16(6, 0, true);
      // Compression method (0 = stored)
      localView.setUint16(8, 0, true);
      // Last mod time/date
      const now = new Date();
      const dosTime = (now.getHours() << 11) | (now.getMinutes() << 5) | (now.getSeconds() >> 1);
      const dosDate = ((now.getFullYear() - 1980) << 9) | ((now.getMonth() + 1) << 5) | now.getDate();
      localView.setUint16(10, dosTime, true);
      localView.setUint16(12, dosDate, true);
      // CRC-32
      localView.setUint32(14, crc32, true);
      // Compressed size
      localView.setUint32(18, contentBytes.length, true);
      // Uncompressed size
      localView.setUint32(22, contentBytes.length, true);
      // Filename length
      localView.setUint16(26, filenameBytes.length, true);
      // Extra field length
      localView.setUint16(28, 0, true);
      // Filename
      for (let i = 0; i < filenameBytes.length; i++) {
        localView.setUint8(30 + i, filenameBytes[i]);
      }
      
      parts.push(localHeader);
      parts.push(contentBytes.buffer);
      
      // Central directory entry
      const centralEntry = new ArrayBuffer(46 + filenameBytes.length);
      const centralView = new DataView(centralEntry);
      
      // Signature
      centralView.setUint32(0, 0x02014b50, true);
      // Version made by
      centralView.setUint16(4, 20, true);
      // Version needed
      centralView.setUint16(6, 20, true);
      // General purpose bit flag
      centralView.setUint16(8, 0, true);
      // Compression method
      centralView.setUint16(10, 0, true);
      // Last mod time/date
      centralView.setUint16(12, dosTime, true);
      centralView.setUint16(14, dosDate, true);
      // CRC-32
      centralView.setUint32(16, crc32, true);
      // Compressed size
      centralView.setUint32(20, contentBytes.length, true);
      // Uncompressed size
      centralView.setUint32(24, contentBytes.length, true);
      // Filename length
      centralView.setUint16(28, filenameBytes.length, true);
      // Extra field length
      centralView.setUint16(30, 0, true);
      // Comment length
      centralView.setUint16(32, 0, true);
      // Disk number start
      centralView.setUint16(34, 0, true);
      // Internal file attributes
      centralView.setUint16(36, 0, true);
      // External file attributes
      centralView.setUint32(38, 0, true);
      // Relative offset of local header
      centralView.setUint32(42, offset, true);
      // Filename
      for (let i = 0; i < filenameBytes.length; i++) {
        centralView.setUint8(46 + i, filenameBytes[i]);
      }
      
      centralDirectory.push(centralEntry);
      offset += localHeader.byteLength + contentBytes.length;
    }
    
    // End of central directory record
    const cdSize = centralDirectory.reduce((sum, entry) => sum + entry.byteLength, 0);
    const cdOffset = offset;
    const totalEntries = files.length;
    
    const eocd = new ArrayBuffer(22);
    const eocdView = new DataView(eocd);
    
    // Signature
    eocdView.setUint32(0, 0x06054b50, true);
    // Disk number
    eocdView.setUint16(4, 0, true);
    // Disk with central directory
    eocdView.setUint16(6, 0, true);
    // Number of entries on this disk
    eocdView.setUint16(8, totalEntries, true);
    // Total number of entries
    eocdView.setUint16(10, totalEntries, true);
    // Size of central directory
    eocdView.setUint32(12, cdSize, true);
    // Offset of central directory
    eocdView.setUint32(16, cdOffset, true);
    // Comment length
    eocdView.setUint16(20, 0, true);
    
    // Combine all parts
    const totalSize = parts.reduce((sum, part) => sum + part.byteLength, 0) + cdSize + 22;
    const zipBuffer = new Uint8Array(totalSize);
    let pos = 0;
    
    for (const part of parts) {
      zipBuffer.set(new Uint8Array(part), pos);
      pos += part.byteLength;
    }
    
    for (const entry of centralDirectory) {
      zipBuffer.set(new Uint8Array(entry), pos);
      pos += entry.byteLength;
    }
    
    zipBuffer.set(new Uint8Array(eocd), pos);
    
    // Download ZIP file
    const blob = new Blob([zipBuffer], { type: 'application/zip' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = zipFilename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  }
  
  // Calculate CRC-32 checksum
  function calculateCRC32(data) {
    let crc = 0xFFFFFFFF;
    const table = getCRC32Table();
    
    for (let i = 0; i < data.length; i++) {
      crc = (crc >>> 8) ^ table[(crc ^ data[i]) & 0xFF];
    }
    
    return (crc ^ 0xFFFFFFFF) >>> 0;
  }
  
  // CRC-32 lookup table
  let crc32Table = null;
  function getCRC32Table() {
    if (crc32Table) return crc32Table;
    
    crc32Table = new Uint32Array(256);
    for (let i = 0; i < 256; i++) {
      let c = i;
      for (let j = 0; j < 8; j++) {
        c = (c & 1) ? (0xEDB88320 ^ (c >>> 1)) : (c >>> 1);
      }
      crc32Table[i] = c;
    }
    return crc32Table;
  }

  // Configure generator settings
  function configure(options) {
    Object.assign(CONFIG, options);
  }

  return { build, downloadAs, configure, CONFIG };
})();
