// ============================================================================
// Element: Underframe (подстолье) — physical leg frames only, no control
// panel (see the separate Пульт element below for that). Vector data
// imported from ArtCAM-exported SVGs, one per size variant (60 / 70), using
// the same Bézier-to-bulge conversion as the wireless charger, extended to
// detect circular holes encoded as 4-segment cubic-Bézier approximations
// (the standard "kappa" construction CAD tools use to draw circles with
// Béziers) — these convert losslessly to exact 2-vertex bulge circles
// rather than being tessellated.
//
// The source file's combined frame+pult drawing was vertically flipped as
// a single rigid unit (not per-piece) before being split into these two
// elements, since the panel was originally authored above the frame and
// needs to end up below it — flipping preserves their relative geometry
// exactly, which independent per-piece flips would risk breaking. Winding
// direction was independently re-verified per contour after the flip
// (checked via signed area / bulge sign, not assumed), since a reflection
// reverses winding and some source contours already wound differently from
// others before any transform was applied.
//
// The right-hand leg is generated by mirroring the left-hand data across a
// vertical axis; mirroring, like the flip above, reverses winding and gets
// the same re-verification.
//
// Local coordinate convention: x=0 at the frame's own left edge, y=0 at the
// frame's own TOP edge (growing downward). The frame is centered vertically
// on the tabletop by default (a vertical inset of 0), with the inset then
// shifting it up or down from that centered position — see buildContours
// for the exact placement math.
//
// Layers: physical parts (leg profile) go on UNDERFRAME; mounting holes
// (присадка) go on UNDERFRAME_HOLES, so a CAM operator can isolate cut
// paths from reference holes.
// ============================================================================
Elements.register((() => {
  const UNDERFRAME_VARIANTS = {
    '60': {
      sku: 'ПОДСТ-60',
      label: 'Подстолье 60',
      width: 503, height: 575,
      parts: [
        { verts: [{x:240.5,y:336,bulge:0},{x:265.5,y:336,bulge:0},{x:265.5,y:239,bulge:0},{x:240.5,y:239,bulge:0}], layer: 'PHYSICAL' },
        { verts: [{x:37.5,y:356,bulge:0},{x:503,y:356,bulge:0},{x:503,y:336,bulge:0},{x:37.5,y:336,bulge:0}], layer: 'PHYSICAL' },
        { verts: [{x:37.5,y:336,bulge:0},{x:199,y:336,bulge:0},{x:199,y:239,bulge:0},{x:37.5,y:239,bulge:0}], layer: 'PHYSICAL' },
        { verts: [{x:0,y:575,bulge:0},{x:37.5,y:575,bulge:0},{x:37.5,y:0,bulge:0},{x:0,y:0,bulge:0}], layer: 'PHYSICAL' },
        { verts: [{x:478,y:336,bulge:0},{x:503,y:336,bulge:0},{x:503,y:239,bulge:0},{x:478,y:239,bulge:0}], layer: 'PHYSICAL' },
        { verts: [{x:37.5,y:239,bulge:0},{x:503,y:239,bulge:0},{x:503,y:219,bulge:0},{x:37.5,y:219,bulge:0}], layer: 'PHYSICAL' },
        { verts: [{x:23,y:20,bulge:1},{x:32,y:20,bulge:1}], layer: 'HOLES' },
        { verts: [{x:21.5,y:20,bulge:1},{x:33.5,y:20,bulge:1}], layer: 'HOLES' },
        { verts: [{x:23,y:425,bulge:1},{x:32,y:425,bulge:1}], layer: 'HOLES' },
        { verts: [{x:21.5,y:425,bulge:1},{x:33.5,y:425,bulge:1}], layer: 'HOLES' },
        { verts: [{x:23,y:150,bulge:1},{x:32,y:150,bulge:1}], layer: 'HOLES' },
        { verts: [{x:21.5,y:150,bulge:1},{x:33.5,y:150,bulge:1}], layer: 'HOLES' },
        { verts: [{x:23,y:555,bulge:1},{x:32,y:555,bulge:1}], layer: 'HOLES' },
        { verts: [{x:21.5,y:555,bulge:1},{x:33.5,y:555,bulge:1}], layer: 'HOLES' },
        { verts: [{x:248.5,y:287.5,bulge:1},{x:257.5,y:287.5,bulge:1}], layer: 'HOLES' },
        { verts: [{x:247,y:287.5,bulge:1},{x:259,y:287.5,bulge:1}], layer: 'HOLES' },
        { verts: [{x:486,y:287.5,bulge:1},{x:495,y:287.5,bulge:1}], layer: 'HOLES' },
        { verts: [{x:484.5,y:287.5,bulge:1},{x:496.5,y:287.5,bulge:1}], layer: 'HOLES' },
      ],
    },
    'X2DM-PRO': {
      sku: 'X2DM-PRO',
      label: 'Подстолье',
      width: 504, height: 700,
      parts: [
      { verts: [{x:504,y:281.5,bulge:0},{x:479,y:281.5,bulge:0},{x:479,y:418.5,bulge:0},{x:504,y:418.5,bulge:0}], layer: 'PHYSICAL' },
      { verts: [{x:36,y:301.5,bulge:0},{x:479,y:301.5,bulge:0},{x:479,y:281.5,bulge:0},{x:36,y:281.5,bulge:0}], layer: 'PHYSICAL' },
      { verts: [{x:36,y:418.5,bulge:0},{x:479,y:418.5,bulge:0},{x:479,y:398.5,bulge:0},{x:36,y:398.5,bulge:0}], layer: 'PHYSICAL' },
      { verts: [{x:36,y:397.5,bulge:0},{x:177,y:397.5,bulge:-0.414214},{x:182,y:392.5,bulge:0},{x:182,y:307.5,bulge:-0.414214},{x:177,y:302.5,bulge:0},{x:36,y:302.5,bulge:0}], layer: 'PHYSICAL' },
      { verts: [{x:16,y:62.5,bulge:0},{x:0,y:62.5,bulge:0},{x:0,y:637.5,bulge:0},{x:16,y:637.5,bulge:-0.414214},{x:36,y:617.5,bulge:0},{x:36,y:82.5,bulge:-0.414214}], layer: 'PHYSICAL' },
      { verts: [{x:5,y:0,bulge:0},{x:65,y:0,bulge:0.414214},{x:70,y:5,bulge:0},{x:70,y:25,bulge:0},{x:0,y:25,bulge:0},{x:0,y:5,bulge:0.414214}], layer: 'PHYSICAL' },
      { verts: [{x:0,y:25,bulge:0},{x:0,y:675,bulge:0},{x:70,y:675,bulge:0},{x:70,y:25,bulge:0}], layer: 'PHYSICAL' },
      { verts: [{x:5,y:700,bulge:0},{x:65,y:700,bulge:-0.414214},{x:70,y:695,bulge:0},{x:70,y:675,bulge:0},{x:0,y:675,bulge:0},{x:0,y:695,bulge:-0.414214}], layer: 'PHYSICAL' },
      { verts: [{x:21.5,y:409.75,bulge:-0.414214},{x:22.75,y:408.5,bulge:-0.414214},{x:21.5,y:407.25,bulge:-0.414214},{x:20.25,y:408.5,bulge:-0.414214}], layer: 'PHYSICAL' },
      { verts: [{x:21.5,y:404.75,bulge:0.414214},{x:25.25,y:408.5,bulge:0.414214},{x:21.5,y:412.25,bulge:0.414214},{x:17.75,y:408.5,bulge:0.414214}], layer: 'PHYSICAL' },
      { verts: [{x:21.5,y:402,bulge:0.414214},{x:28,y:408.5,bulge:0.414214},{x:21.5,y:415,bulge:0.414214},{x:15,y:408.5,bulge:0.414214}], layer: 'PHYSICAL' },
      { verts: [{x:21.5,y:292.75,bulge:-0.414214},{x:22.75,y:291.5,bulge:-0.414214},{x:21.5,y:290.25,bulge:-0.414214},{x:20.25,y:291.5,bulge:-0.414214}], layer: 'PHYSICAL' },
      { verts: [{x:21.5,y:287.75,bulge:0.414214},{x:25.25,y:291.5,bulge:0.414214},{x:21.5,y:295.25,bulge:0.414214},{x:17.75,y:291.5,bulge:0.414214}], layer: 'PHYSICAL' },
      { verts: [{x:21.5,y:285,bulge:0.414214},{x:28,y:291.5,bulge:0.414214},{x:21.5,y:298,bulge:0.414214},{x:15,y:291.5,bulge:0.414214}], layer: 'PHYSICAL' },
      { verts: [{x:15.5,y:182.5,bulge:0.414214},{x:21.5,y:176.5,bulge:0.414214},{x:27.5,y:182.5,bulge:0.414214},{x:21.5,y:188.5,bulge:0.414214}], layer: 'HOLES' },
      { verts: [{x:17,y:182.5,bulge:0.414214},{x:21.5,y:178,bulge:0.414214},{x:26,y:182.5,bulge:0.414214},{x:21.5,y:187,bulge:0.414214}], layer: 'HOLES' },
      { verts: [{x:15.5,y:82.5,bulge:0.414214},{x:21.5,y:76.5,bulge:0.414214},{x:27.5,y:82.5,bulge:0.414214},{x:21.5,y:88.5,bulge:0.414214}], layer: 'HOLES' },
      { verts: [{x:17,y:82.5,bulge:0.414214},{x:21.5,y:78,bulge:0.414214},{x:26,y:82.5,bulge:0.414214},{x:21.5,y:87,bulge:0.414214}], layer: 'HOLES' },
      { verts: [{x:15.5,y:617.5,bulge:0.414214},{x:21.5,y:611.5,bulge:0.414214},{x:27.5,y:617.5,bulge:0.414214},{x:21.5,y:623.5,bulge:0.414214}], layer: 'HOLES' },
      { verts: [{x:17,y:617.5,bulge:0.414214},{x:21.5,y:613,bulge:0.414214},{x:26,y:617.5,bulge:0.414214},{x:21.5,y:622,bulge:0.414214}], layer: 'HOLES' },
      { verts: [{x:15.5,y:517.5,bulge:0.414214},{x:21.5,y:511.5,bulge:0.414214},{x:27.5,y:517.5,bulge:0.414214},{x:21.5,y:523.5,bulge:0.414214}], layer: 'HOLES' },
      { verts: [{x:17,y:517.5,bulge:0.414214},{x:21.5,y:513,bulge:0.414214},{x:26,y:517.5,bulge:0.414214},{x:21.5,y:522,bulge:0.414214}], layer: 'HOLES' },
      { verts: [{x:485.5,y:350,bulge:0.414214},{x:491.5,y:344,bulge:0.414214},{x:497.5,y:350,bulge:0.414214},{x:491.5,y:356,bulge:0.414214}], layer: 'HOLES' },
      { verts: [{x:487,y:350,bulge:0.414214},{x:491.5,y:345.5,bulge:0.414214},{x:496,y:350,bulge:0.414214},{x:491.5,y:354.5,bulge:0.414214}], layer: 'HOLES' },
      ],
    },
    '70': {
      sku: 'ПОДСТ-70',
      label: 'Подстолье 70',
      width: 548, height: 575,
      parts: [
        { verts: [{x:278,y:367.5,bulge:0},{x:298,y:367.5,bulge:0},{x:298,y:207.5,bulge:0},{x:278,y:207.5,bulge:0}], layer: 'PHYSICAL' },
        { verts: [{x:38,y:387.5,bulge:0},{x:548,y:387.5,bulge:0},{x:548,y:367.5,bulge:0},{x:38,y:367.5,bulge:0}], layer: 'PHYSICAL' },
        { verts: [{x:0,y:575,bulge:0},{x:38,y:575,bulge:0},{x:38,y:0,bulge:0},{x:0,y:0,bulge:0}], layer: 'PHYSICAL' },
        { verts: [{x:38,y:207.5,bulge:0},{x:548,y:207.5,bulge:0},{x:548,y:187.5,bulge:0},{x:38,y:187.5,bulge:0}], layer: 'PHYSICAL' },
        { verts: [{x:528,y:367.5,bulge:0},{x:548,y:367.5,bulge:0},{x:548,y:207.5,bulge:0},{x:528,y:207.5,bulge:0}], layer: 'PHYSICAL' },
        { verts: [{x:23.5,y:20,bulge:1},{x:32.5,y:20,bulge:1}], layer: 'HOLES' },
        { verts: [{x:22,y:20,bulge:1},{x:34,y:20,bulge:1}], layer: 'HOLES' },
        { verts: [{x:23.5,y:425,bulge:1},{x:32.5,y:425,bulge:1}], layer: 'HOLES' },
        { verts: [{x:22,y:425,bulge:1},{x:34,y:425,bulge:1}], layer: 'HOLES' },
        { verts: [{x:23.5,y:150,bulge:1},{x:32.5,y:150,bulge:1}], layer: 'HOLES' },
        { verts: [{x:22,y:150,bulge:1},{x:34,y:150,bulge:1}], layer: 'HOLES' },
        { verts: [{x:23.5,y:555,bulge:1},{x:32.5,y:555,bulge:1}], layer: 'HOLES' },
        { verts: [{x:22,y:555,bulge:1},{x:34,y:555,bulge:1}], layer: 'HOLES' },
        { verts: [{x:283.5,y:287.5,bulge:1},{x:292.5,y:287.5,bulge:1}], layer: 'HOLES' },
        { verts: [{x:282,y:287.5,bulge:1},{x:294,y:287.5,bulge:1}], layer: 'HOLES' },
        { verts: [{x:533.5,y:287.5,bulge:1},{x:542.5,y:287.5,bulge:1}], layer: 'HOLES' },
        { verts: [{x:532,y:287.5,bulge:1},{x:544,y:287.5,bulge:1}], layer: 'HOLES' },
      ],
    },
  };
  
  function ensureCCW(verts){
    if (verts.length < 2) return verts;
    if (verts.length === 2) return verts[0].bulge > 0 ? verts : Geo.reverseContour(verts);
    return Geo.signedArea(verts) >= 0 ? verts : Geo.reverseContour(verts);
  }

  function mirrorX(verts, axisX){
    const mirrored = verts.map(v => ({ x: 2 * axisX - v.x, y: v.y, bulge: -v.bulge }));
    return ensureCCW(mirrored);
  }

  // Builds one leg-side's geometry at a given placement, optionally
  // mirrored. `leftX` is where this side's local x=0 lands on the
  // tabletop; `topY` is where this side's local y=0 (the frame's own top
  // edge) lands — i.e. the tabletop's top edge minus the vertical inset.
  function buildSide(data, leftX, topY, mirror){
    const place = (verts) => {
      let v = verts;
      if (mirror) v = mirrorX(v, data.width / 2);
      // local y grows downward from the frame's own top (y=0), so placing
      // it needs a Y flip relative to translate's plain add: worldY =
      // topY - localY. A Y flip reverses the winding direction, which
      // requires inverting all bulge signs to preserve the arc direction.
      return v.map(pt => ({
        x: pt.x + leftX,
        y: topY - pt.y,
        bulge: -pt.bulge, // Y-flip reverses arc direction
      }));
    };
    const entries = [];
    for (const { verts, layer } of data.parts) {
      entries.push({ contour: ensureCCW(place(verts)), layer });
    }
    return entries;
  }

  function buildContours(p){
    if (!p.underframeType || p.underframeType === 'none') return [];
    const data = UNDERFRAME_VARIANTS[p.underframeType];
    if (!data) return [];

    const insetH = p.underframeInsetH != null ? p.underframeInsetH : 50;
    // Centered vertically by default (insetV=0): the frame's own vertical
    // midpoint lands on the tabletop's own vertical midpoint. insetV then
    // shifts it from that centered position — positive moves the frame up,
    // negative moves it down, matching this app's normal CAD Y-up
    // convention (unlike the charger's always-non-negative inset system,
    // there's no single anchor corner here to derive a sign from, so this
    // stays a plain signed offset from center).
    const insetV = p.underframeInsetV || 0;
    const topY = p.H / 2 + data.height / 2 + insetV;

    const entries = [];
    entries.push(...buildSide(data, insetH, topY, false));
    entries.push(...buildSide(data, p.W - insetH - data.width, topY, true));
    return entries;
  }

  return { id: 'underframe', buildContours, VARIANTS: UNDERFRAME_VARIANTS };
})());

// The underframe's own type <select> lives as static markup in
// index.html (it isn't a repeatable/embeddable element like the ones
// built via UI.createEmbeddableManager, so it doesn't go through
// optionsFromVariants in element-managers.js) — but its OPTIONS are
// still generated here, from UNDERFRAME_VARIANTS's own sku/label, so a
// new underframe size only ever needs adding to UNDERFRAME_VARIANTS
// above, never a second hand-edit in the HTML. The "Нет подстолья" (no
// underframe) option is kept as static markup in index.html since it
// isn't a real variant. Runs at script-load time, safely before
// app-render.js reads the select's value on first render (this file
// loads earlier in index.html's own script order).
// Default underframe size on a fresh (unsaved) project — kept as one
// named constant here rather than a hardcoded `selected` attribute in
// index.html's markup, since the HTML no longer lists '60'/'70' as
// static options at all (see below). Must be a real key of
// UNDERFRAME_VARIANTS.
const UNDERFRAME_DEFAULT_TYPE = '60';

(function populateUnderframeTypeOptions(){
  const select = document.getElementById('underframeType');
  if (!select) return;
  // UNDERFRAME_VARIANTS itself is local to the IIFE above (not global —
  // this file deliberately keeps it out of the global scope other
  // element files' top-level consts sit in), so it's read back the same
  // way dimensions.js already does: via the registered element's own
  // .VARIANTS, exposed by the `return { id, buildContours, VARIANTS }`
  // just above.
  const variants = Elements.all().find(e => e.id === 'underframe').VARIANTS;
  const previousValue = select.value; // 'none', the only static option
  for (const key of Object.keys(variants)) {
    if (select.querySelector(`option[value="${key}"]`)) continue; // don't duplicate on re-run
    const v = variants[key];
    const option = document.createElement('option');
    option.value = key;
    option.textContent = v.sku && v.label ? `${v.sku} — ${v.label}` : (v.label || v.sku || key);
    select.appendChild(option);
  }
  // A saved project's own value is applied later by app-project.js's own
  // load path, which sets .value directly and doesn't depend on this
  // select's default — this only decides what a brand-new, never-loaded
  // project starts on.
  select.value = (previousValue && previousValue !== 'none') ? previousValue : UNDERFRAME_DEFAULT_TYPE;
})();
