// ============================================================================
// Element: Underframe (подстолье) — physical leg frames only, no control
// panel (see the separate Пульт element below for that). Vector data
// imported from ArtCAM-exported SVGs, one per size variant (60 / 70), using
// the same Bézier-to-bulge conversion as the wireless charger, extended to
// detect circular holes encoded as 4-segment cubic-Bézier approximations
// (the standard "kappa" construction CAD tools use to draw circles with
// Béziers) — these convert losslessly to exact 2-vertex bulge circles
// rather than being tessellated.
//
// The source file's combined frame+pult drawing was vertically flipped as
// a single rigid unit (not per-piece) before being split into these two
// elements, since the panel was originally authored above the frame and
// needs to end up below it — flipping preserves their relative geometry
// exactly, which independent per-piece flips would risk breaking. Winding
// direction was independently re-verified per contour after the flip
// (checked via signed area / bulge sign, not assumed), since a reflection
// reverses winding and some source contours already wound differently from
// others before any transform was applied.
//
// The right-hand leg is generated by mirroring the left-hand data across a
// vertical axis; mirroring, like the flip above, reverses winding and gets
// the same re-verification.
//
// Local coordinate convention: x=0 at the frame's own left edge, y=0 at the
// frame's own TOP edge (growing downward). The frame is centered vertically
// on the tabletop by default (a vertical inset of 0), with the inset then
// shifting it up or down from that centered position — see buildContours
// for the exact placement math.
//
// Layers: physical parts (leg profile) go on UNDERFRAME; mounting holes
// (присадка) go on UNDERFRAME_HOLES, so a CAM operator can isolate cut
// paths from reference holes.
// ============================================================================
Elements.register((() => {
  const UNDERFRAME_VARIANTS = {
    '60': {
      width: 503.0, height: 575.0,
      frameOutline: [[{x:240.5,y:336.0,bulge:0},{x:265.5,y:336.0,bulge:0},{x:265.5,y:239.0,bulge:0},{x:240.5,y:239.0,bulge:0}],[{x:37.5,y:356.0,bulge:0},{x:503.0,y:356.0,bulge:0},{x:503.0,y:336.0,bulge:0},{x:37.5,y:336.0,bulge:0}],[{x:37.5,y:336.0,bulge:0},{x:199.0,y:336.0,bulge:0},{x:199.0,y:239.0,bulge:0},{x:37.5,y:239.0,bulge:0}],[{x:0.0,y:575.0,bulge:0},{x:37.5,y:575.0,bulge:0},{x:37.5,y:0.0,bulge:0},{x:0.0,y:0.0,bulge:0}],[{x:478.0,y:336.0,bulge:0},{x:503.0,y:336.0,bulge:0},{x:503.0,y:239.0,bulge:0},{x:478.0,y:239.0,bulge:0}],[{x:37.5,y:239.0,bulge:0},{x:503.0,y:239.0,bulge:0},{x:503.0,y:219.0,bulge:0},{x:37.5,y:219.0,bulge:0}]],
      frameHoles: [[{x:23.0,y:20.0,bulge:1.0},{x:32.0,y:20.0,bulge:1.0}],[{x:21.5,y:20.0,bulge:1.0},{x:33.5,y:20.0,bulge:1.0}],[{x:23.0,y:425.0,bulge:1.0},{x:32.0,y:425.0,bulge:1.0}],[{x:21.5,y:425.0,bulge:1.0},{x:33.5,y:425.0,bulge:1.0}],[{x:23.0,y:150.0,bulge:1.0},{x:32.0,y:150.0,bulge:1.0}],[{x:21.5,y:150.0,bulge:1.0},{x:33.5,y:150.0,bulge:1.0}],[{x:23.0,y:555.0,bulge:1.0},{x:32.0,y:555.0,bulge:1.0}],[{x:21.5,y:555.0,bulge:1.0},{x:33.5,y:555.0,bulge:1.0}],[{x:248.5,y:287.5,bulge:1.0},{x:257.5,y:287.5,bulge:1.0}],[{x:247.0,y:287.5,bulge:1.0},{x:259.0,y:287.5,bulge:1.0}],[{x:486.0,y:287.5,bulge:1.0},{x:495.0,y:287.5,bulge:1.0}],[{x:484.5,y:287.5,bulge:1.0},{x:496.5,y:287.5,bulge:1.0}]],
    },
    '70': {
      width: 548.0, height: 575.0,
      frameOutline: [[{x:278.0,y:367.5,bulge:0},{x:298.0,y:367.5,bulge:0},{x:298.0,y:207.5,bulge:0},{x:278.0,y:207.5,bulge:0}],[{x:38.0,y:387.5,bulge:0},{x:548.0,y:387.5,bulge:0},{x:548.0,y:367.5,bulge:0},{x:38.0,y:367.5,bulge:0}],[{x:0.0,y:575.0,bulge:0},{x:38.0,y:575.0,bulge:0},{x:38.0,y:0.0,bulge:0},{x:0.0,y:0.0,bulge:0}],[{x:38.0,y:207.5,bulge:0},{x:548.0,y:207.5,bulge:0},{x:548.0,y:187.5,bulge:0},{x:38.0,y:187.5,bulge:0}],[{x:528.0,y:367.5,bulge:0},{x:548.0,y:367.5,bulge:0},{x:548.0,y:207.5,bulge:0},{x:528.0,y:207.5,bulge:0}]],
      frameHoles: [[{x:23.5,y:20.0,bulge:1.0},{x:32.5,y:20.0,bulge:1.0}],[{x:22.0,y:20.0,bulge:1.0},{x:34.0,y:20.0,bulge:1.0}],[{x:23.5,y:425.0,bulge:1.0},{x:32.5,y:425.0,bulge:1.0}],[{x:22.0,y:425.0,bulge:1.0},{x:34.0,y:425.0,bulge:1.0}],[{x:23.5,y:150.0,bulge:1.0},{x:32.5,y:150.0,bulge:1.0}],[{x:22.0,y:150.0,bulge:1.0},{x:34.0,y:150.0,bulge:1.0}],[{x:23.5,y:555.0,bulge:1.0},{x:32.5,y:555.0,bulge:1.0}],[{x:22.0,y:555.0,bulge:1.0},{x:34.0,y:555.0,bulge:1.0}],[{x:283.5,y:287.5,bulge:1.0},{x:292.5,y:287.5,bulge:1.0}],[{x:282.0,y:287.5,bulge:1.0},{x:294.0,y:287.5,bulge:1.0}],[{x:533.5,y:287.5,bulge:1.0},{x:542.5,y:287.5,bulge:1.0}],[{x:532.0,y:287.5,bulge:1.0},{x:544.0,y:287.5,bulge:1.0}]],
    },
  };

  function ensureCCW(verts){
    if (verts.length < 2) return verts;
    if (verts.length === 2) return verts[0].bulge > 0 ? verts : Geo.reverseContour(verts);
    return Geo.signedArea(verts) >= 0 ? verts : Geo.reverseContour(verts);
  }

  function mirrorX(verts, axisX){
    const mirrored = verts.map(v => ({ x: 2 * axisX - v.x, y: v.y, bulge: -v.bulge }));
    return ensureCCW(mirrored);
  }

  // Builds one leg-side's geometry at a given placement, optionally
  // mirrored. `leftX` is where this side's local x=0 lands on the
  // tabletop; `topY` is where this side's local y=0 (the frame's own top
  // edge) lands — i.e. the tabletop's top edge minus the vertical inset.
  function buildSide(data, leftX, topY, mirror){
    const place = (verts) => {
      let v = verts;
      if (mirror) v = mirrorX(v, data.width / 2);
      // local y grows downward from the frame's own top (y=0), so placing
      // it needs a Y flip relative to translate's plain add: worldY =
      // topY - localY.
      return v.map(pt => ({
        x: (mirror ? pt.x : pt.x) + leftX,
        y: topY - pt.y,
        bulge: mirror ? -pt.bulge : pt.bulge, // Y-flip on placement also reverses arc direction
      }));
    };
    const entries = [];
    for (const contour of data.frameOutline) entries.push({ contour: ensureCCW(place(contour)), layer: 'UNDERFRAME' });
    for (const contour of data.frameHoles) entries.push({ contour: ensureCCW(place(contour)), layer: 'UNDERFRAME_HOLES' });
    return entries;
  }

  function buildContours(p){
    if (!p.underframeType || p.underframeType === 'none') return [];
    const data = UNDERFRAME_VARIANTS[p.underframeType];
    if (!data) return [];

    const insetH = p.underframeInsetH != null ? p.underframeInsetH : 50;
    // Centered vertically by default (insetV=0): the frame's own vertical
    // midpoint lands on the tabletop's own vertical midpoint. insetV then
    // shifts it from that centered position — positive moves the frame up,
    // negative moves it down, matching this app's normal CAD Y-up
    // convention (unlike the charger's always-non-negative inset system,
    // there's no single anchor corner here to derive a sign from, so this
    // stays a plain signed offset from center).
    const insetV = p.underframeInsetV || 0;
    const topY = p.H / 2 + data.height / 2 + insetV;

    const entries = [];
    entries.push(...buildSide(data, insetH, topY, false));
    entries.push(...buildSide(data, p.W - insetH - data.width, topY, true));
    return entries;
  }

  return { id: 'underframe', buildContours, VARIANTS: UNDERFRAME_VARIANTS };
})());
