// ============================================================================
// Element: Underframe (подстолье) — physical leg frames only, no control
// panel (see the separate Пульт element below for that). Vector data
// imported from ArtCAM-exported SVGs, one per size variant (60 / 70), using
// the same Bézier-to-bulge conversion as the wireless charger, extended to
// detect circular holes encoded as 4-segment cubic-Bézier approximations
// (the standard "kappa" construction CAD tools use to draw circles with
// Béziers) — these convert losslessly to exact 2-vertex bulge circles
// rather than being tessellated.
//
// The source file's combined frame+pult drawing was vertically flipped as
// a single rigid unit (not per-piece) before being split into these two
// elements, since the panel was originally authored above the frame and
// needs to end up below it — flipping preserves their relative geometry
// exactly, which independent per-piece flips would risk breaking. Winding
// direction was independently re-verified per contour after the flip
// (checked via signed area / bulge sign, not assumed), since a reflection
// reverses winding and some source contours already wound differently from
// others before any transform was applied.
//
// The right-hand leg is generated by mirroring the left-hand data across a
// vertical axis; mirroring, like the flip above, reverses winding and gets
// the same re-verification.
//
// Local coordinate convention (AFTER geometry refactor): The geometry data
// should be authored with its local origin (0,0) at the center of the LEFT
// edge for the left leg variant. For positioning purposes, this means:
//   - The 'left' anchor places the leg's left-edge-center at the specified inset
//   - The 'right' anchor places the leg's right-edge-center (after mirroring)
//     at the specified inset from the right tabletop edge
//   - Vertical positioning uses underframeInsetV as a signed offset from the
//     tabletop's vertical center (positive = up, negative = down)
// This allows the underframe to use the same anchor+inset positioning system
// as all other embeddable elements, unifying the code path and making it
// independent of the specific geometry dimensions.
//
// Layers: physical parts (leg profile) go on PHYSICAL; mounting holes
// (присадка) are built via Holes.at() (see js/elements/hole.js), which
// places each hole+counterbore pair on its own HOLE_A/HOLE_A_CS or
// HOLE_B/HOLE_B_CS layer depending on fastener size, so a CAM operator
// can isolate cut paths per hole size.
// ============================================================================
Elements.register((() => {
  const UNDERFRAME_VARIANTS = {
    '60': {
      sku: 'ПОДСТ-60',
      label: 'Подстолье 60',
      width: 503, height: 575,
      parts: [
      { verts: [{x:240.5,y:48.5,bulge:0},{x:265.5,y:48.5,bulge:0},{x:265.5,y:-48.5,bulge:0},{x:240.5,y:-48.5,bulge:0}], layer: 'PHYSICAL' },
      { verts: [{x:37.5,y:68.5,bulge:0},{x:503,y:68.5,bulge:0},{x:503,y:48.5,bulge:0},{x:37.5,y:48.5,bulge:0}], layer: 'PHYSICAL' },
      { verts: [{x:37.5,y:48.5,bulge:0},{x:199,y:48.5,bulge:0},{x:199,y:-48.5,bulge:0},{x:37.5,y:-48.5,bulge:0}], layer: 'PHYSICAL' },
      { verts: [{x:0,y:287.5,bulge:0},{x:37.5,y:287.5,bulge:0},{x:37.5,y:-287.5,bulge:0},{x:0,y:-287.5,bulge:0}], layer: 'PHYSICAL' },
      { verts: [{x:478,y:48.5,bulge:0},{x:503,y:48.5,bulge:0},{x:503,y:-48.5,bulge:0},{x:478,y:-48.5,bulge:0}], layer: 'PHYSICAL' },
      { verts: [{x:37.5,y:-48.5,bulge:0},{x:503,y:-48.5,bulge:0},{x:503,y:-68.5,bulge:0},{x:37.5,y:-68.5,bulge:0}], layer: 'PHYSICAL' },
      ...Holes.at(27.5, -267.5, 'A'),
      ...Holes.at(27.5, 137.5, 'A'),
      ...Holes.at(27.5, -137.5, 'A'),
      ...Holes.at(27.5, 267.5, 'A'),
      ...Holes.at(253, 0, 'A'),
      ...Holes.at(490.5, 0, 'A'),
      ],
    },
    'X2DM-PRO': {
      sku: 'X2DM-PRO',
      label: 'Подстолье',
      width: 504, height: 700,
      parts: [
      { verts: [{x:504,y:-68.5,bulge:0},{x:479,y:-68.5,bulge:0},{x:479,y:68.5,bulge:0},{x:504,y:68.5,bulge:0}], layer: 'PHYSICAL' },
      { verts: [{x:36,y:-48.5,bulge:0},{x:479,y:-48.5,bulge:0},{x:479,y:-68.5,bulge:0},{x:36,y:-68.5,bulge:0}], layer: 'PHYSICAL' },
      { verts: [{x:36,y:68.5,bulge:0},{x:479,y:68.5,bulge:0},{x:479,y:48.5,bulge:0},{x:36,y:48.5,bulge:0}], layer: 'PHYSICAL' },
      { verts: [{x:36,y:47.5,bulge:0},{x:177,y:47.5,bulge:-0.414214},{x:182,y:42.5,bulge:0},{x:182,y:-42.5,bulge:-0.414214},{x:177,y:-47.5,bulge:0},{x:36,y:-47.5,bulge:0}], layer: 'PHYSICAL' },
      { verts: [{x:16,y:-287.5,bulge:0},{x:0,y:-287.5,bulge:0},{x:0,y:287.5,bulge:0},{x:16,y:287.5,bulge:-0.414214},{x:36,y:267.5,bulge:0},{x:36,y:-267.5,bulge:-0.414214}], layer: 'PHYSICAL' },
      { verts: [{x:5,y:-350,bulge:0},{x:65,y:-350,bulge:0.414214},{x:70,y:-345,bulge:0},{x:70,y:-325,bulge:0},{x:0,y:-325,bulge:0},{x:0,y:-345,bulge:0.414214}], layer: 'PHYSICAL' },
      { verts: [{x:0,y:-325,bulge:0},{x:0,y:325,bulge:0},{x:70,y:325,bulge:0},{x:70,y:-325,bulge:0}], layer: 'PHYSICAL' },
      { verts: [{x:5,y:350,bulge:0},{x:65,y:350,bulge:-0.414214},{x:70,y:345,bulge:0},{x:70,y:325,bulge:0},{x:0,y:325,bulge:0},{x:0,y:345,bulge:-0.414214}], layer: 'PHYSICAL' },
      { verts: [{x:21.5,y:59.75,bulge:-0.414214},{x:22.75,y:58.5,bulge:-0.414214},{x:21.5,y:57.25,bulge:-0.414214},{x:20.25,y:58.5,bulge:-0.414214}], layer: 'PHYSICAL' },
      { verts: [{x:21.5,y:54.75,bulge:0.414214},{x:25.25,y:58.5,bulge:0.414214},{x:21.5,y:62.25,bulge:0.414214},{x:17.75,y:58.5,bulge:0.414214}], layer: 'PHYSICAL' },
      { verts: [{x:21.5,y:52,bulge:0.414214},{x:28,y:58.5,bulge:0.414214},{x:21.5,y:65,bulge:0.414214},{x:15,y:58.5,bulge:0.414214}], layer: 'PHYSICAL' },
      { verts: [{x:21.5,y:-57.25,bulge:-0.414214},{x:22.75,y:-58.5,bulge:-0.414214},{x:21.5,y:-59.75,bulge:-0.414214},{x:20.25,y:-58.5,bulge:-0.414214}], layer: 'PHYSICAL' },
      { verts: [{x:21.5,y:-62.25,bulge:0.414214},{x:25.25,y:-58.5,bulge:0.414214},{x:21.5,y:-54.75,bulge:0.414214},{x:17.75,y:-58.5,bulge:0.414214}], layer: 'PHYSICAL' },
      { verts: [{x:21.5,y:-65,bulge:0.414214},{x:28,y:-58.5,bulge:0.414214},{x:21.5,y:-52,bulge:0.414214},{x:15,y:-58.5,bulge:0.414214}], layer: 'PHYSICAL' },
      ...Holes.at(21.5, -167.5, 'A'),
      ...Holes.at(21.5, -267.5, 'A'),
      ...Holes.at(21.5, 267.5, 'A'),
      ...Holes.at(21.5, 167.5, 'A'),
      ...Holes.at(491.5, 0, 'A'),
      ],
    },
    '70': {
      sku: 'ПОДСТ-70',
      label: 'Подстолье 70',
      width: 548, height: 575,
      parts: [
      { verts: [{x:278,y:80,bulge:0},{x:298,y:80,bulge:0},{x:298,y:-80,bulge:0},{x:278,y:-80,bulge:0}], layer: 'PHYSICAL' },
      { verts: [{x:38,y:100,bulge:0},{x:548,y:100,bulge:0},{x:548,y:80,bulge:0},{x:38,y:80,bulge:0}], layer: 'PHYSICAL' },
      { verts: [{x:0,y:287.5,bulge:0},{x:38,y:287.5,bulge:0},{x:38,y:-287.5,bulge:0},{x:0,y:-287.5,bulge:0}], layer: 'PHYSICAL' },
      { verts: [{x:38,y:-80,bulge:0},{x:548,y:-80,bulge:0},{x:548,y:-100,bulge:0},{x:38,y:-100,bulge:0}], layer: 'PHYSICAL' },
      { verts: [{x:528,y:80,bulge:0},{x:548,y:80,bulge:0},{x:548,y:-80,bulge:0},{x:528,y:-80,bulge:0}], layer: 'PHYSICAL' },
      ...Holes.at(28, -267.5, 'A'),
      ...Holes.at(28, 137.5, 'A'),
      ...Holes.at(28, -137.5, 'A'),
      ...Holes.at(28, 267.5, 'A'),
      ...Holes.at(288, 0, 'A'),
      ...Holes.at(538, 0, 'A'),
      ],
    },
  };
  
  // Builds one leg-side's geometry at a given placement, optionally
  // mirrored. The underframe geometry is authored with its local origin
  // (0,0) at the center of the left edge for the left leg. For the right
  // leg (mirrored), this means the local origin ends up at the center of
  // the right edge after mirroring. This allows positioning via the
  // standard anchor system ('left'/'right') where insetX is the distance
  // from the tabletop edge inward, and insetY is a vertical offset from
  // the centered position.
  function buildSide(data, centerX, centerY, mirrorX){
    const entries = [];
    for (const { verts, layer } of data.parts) {
      let v = verts;
      // Mirror across the vertical axis at x=0 for the right leg.
      // Geo.mirror handles bulge sign flip and winding reversal.
      if (mirrorX) {
        v = Geo.mirror(v, 'vertical', { x: 0, y: 0 });
      }
      // Y flip: local y grows downward from frame's top, world y grows up.
      // A Y flip reverses winding direction, requiring bulge sign inversion.
      v = v.map(pt => ({ x: pt.x, y: -pt.y, bulge: -pt.bulge }));
      // Translate to final position
      v = Geo.translate(v, centerX, centerY);
      entries.push({ contour: v, layer });
    }
    return entries;
  }

  function buildContours(p){
    if (!p.underframeType || p.underframeType === 'none') return [];
    const data = UNDERFRAME_VARIANTS[p.underframeType];
    if (!data) return [];

    const bounds = { minX: 0, minY: 0, maxX: p.W, maxY: p.H };
        
    const leftPos = Elements.resolveInset('left', p.underframeInsetH || 0, p.underframeInsetV || 0, bounds);
    const rightPos = Elements.resolveInset('right', p.underframeInsetH || 0, p.underframeInsetV || 0, bounds);

    const entries = [];
    entries.push(...buildSide(data, leftPos.x, leftPos.y, false));
    entries.push(...buildSide(data, rightPos.x, rightPos.y, true));
    return entries;
  }

  return { id: 'underframe', buildContours, VARIANTS: UNDERFRAME_VARIANTS };
})());

// The underframe's own type <select> lives as static markup in
// index.html (it isn't a repeatable/embeddable element like the ones
// built via UI.createEmbeddableManager, so it doesn't go through
// optionsFromVariants in element-managers.js) — but its OPTIONS are
// still generated here, from UNDERFRAME_VARIANTS's own sku/label, so a
// new underframe size only ever needs adding to UNDERFRAME_VARIANTS
// above, never a second hand-edit in the HTML. The "Нет подстолья" (no
// underframe) option is kept as static markup in index.html since it
// isn't a real variant. Runs at script-load time, safely before
// app-render.js reads the select's value on first render (this file
// loads earlier in index.html's own script order).
// Default underframe size on a fresh (unsaved) project — kept as one
// named constant here rather than a hardcoded `selected` attribute in
// index.html's markup, since the HTML no longer lists '60'/'70' as
// static options at all (see below). Must be a real key of
// UNDERFRAME_VARIANTS.
const UNDERFRAME_DEFAULT_TYPE = '60';

(function populateUnderframeTypeOptions(){
  const select = document.getElementById('underframeType');
  if (!select) return;
  // UNDERFRAME_VARIANTS itself is local to the IIFE above (not global —
  // this file deliberately keeps it out of the global scope other
  // element files' top-level consts sit in), so it's read back the same
  // way dimensions.js already does: via the registered element's own
  // .VARIANTS, exposed by the `return { id, buildContours, VARIANTS }`
  // just above.
  const variants = Elements.all().find(e => e.id === 'underframe').VARIANTS;
  const previousValue = select.value; // 'none', the only static option
  for (const key of Object.keys(variants)) {
    if (select.querySelector(`option[value="${key}"]`)) continue; // don't duplicate on re-run
    const v = variants[key];
    const option = document.createElement('option');
    option.value = key;
    option.textContent = v.sku && v.label ? `${v.sku} — ${v.label}` : (v.label || v.sku || key);
    select.appendChild(option);
  }
  // A saved project's own value is applied later by app-project.js's own
  // load path, which sets .value directly and doesn't depend on this
  // select's default — this only decides what a brand-new, never-loaded
  // project starts on.
  select.value = (previousValue && previousValue !== 'none') ? previousValue : UNDERFRAME_DEFAULT_TYPE;
})();
